package com.collabera.jump;

import java.util.Arrays;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be: [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n],
// By considering the terms in the Fibonacci sequence whose values do not exceed four "
// million, find the sum of the even-valued terms, using while loop"

public class Fibonacci {

	public static void main(String[] args) {
		
		long fibo1= 0, 
			fibo2= 1,
			limit= 4000000,
			sum= 0;

		
		while(fibo2<limit) {
			if((fibo1+fibo2)%2==0) sum += fibo1+fibo2;
			
			fibo2=fibo1+fibo2;
			fibo1=fibo2-fibo1;

		}
		
		System.out.println("The sum of the even values in the fibonacci sequence "
				+ "not exceeding " + limit + " is " + sum);

	}

}
